export const BUILDER_NAV_SIZE = '50px'
export const BUILDER_NAV_SIZE_SM = '35px'
export const BUILDER_DEFAULT_SPACING = '0.5rem'
export const BUILDER_DEFAULT_SPACING_LG = '1rem'
export const DEFAULT_FRAME_COLOR = '#ffff'
